version: "3"

services:
  client-app:
    image: client-app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "wavespace-app"
  server-app:
    image: server-app
    ports:
      - "5000:5000"
    networks:
      - "wavespace-app"

networks:
    wavespace-app:
      driver: bridge