name: Build Containers for Prod & Push to Dockerhub

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-deploy-back:
    name: Build and Deploy Back-end
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          context: .
          file: ./server/Dockerfile
          #platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            americoc/ota-backend:latest

  build-and-deploy-front:
    name: Build and Deploy Front-end
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
  
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          context: .
          file: ./client/Dockerfile
          #platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            americoc/ota-frontend:latest
